"""add text search vector to document chunk

Revision ID: 59fc888051cc
Revises: 5c449c82c5a0
Create Date: 2026-08-30 23:00:24.037602

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '59fc888051cc'
down_revision: Union[str, Sequence[str], None] = '5c449c82c5a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document_chunks', sa.Column('text_search_vector', postgresql.TSVECTOR(), nullable=True))
    op.create_index('ix_document_chunks_text_search_vector', 'document_chunks', ['text_search_vector'], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###
    
    # Custom trigger to auto-update TSVECTOR
    op.execute("""
        CREATE OR REPLACE FUNCTION document_chunks_tsvector_trigger() RETURNS trigger AS $$
        begin
          new.text_search_vector := to_tsvector('english', new.text);
          return new;
        end
        $$ LANGUAGE plpgsql;
    """)
    op.execute("""
        CREATE TRIGGER tsvectorupdate BEFORE INSERT OR UPDATE
        ON document_chunks FOR EACH ROW EXECUTE PROCEDURE document_chunks_tsvector_trigger();
    """)


def downgrade() -> None:
    """Downgrade schema."""
    op.execute("DROP TRIGGER IF EXISTS tsvectorupdate ON document_chunks;")
    op.execute("DROP FUNCTION IF EXISTS document_chunks_tsvector_trigger();")
    
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_document_chunks_text_search_vector', table_name='document_chunks', postgresql_using='gin')
    op.drop_column('document_chunks', 'text_search_vector')
    # ### end Alembic commands ###
